permalink: /blog/:year/:month/:day/:title
markdown: kramdown
kramdown:
    input: GFM
    auto_ids: true
    hard_wrap: false
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        css_class: "highlight"
